### ISSUE TITLE
Nothing is displayed on screen while running the project locally

### ISSUE THREAD

**Issue by iAmmarTahir** [Mamboleoo/SurfaceSampling#1]
I have followed the steps mentioned in README.md but when I run `npm start`, no model is rendered on the screen and I just see a black screen
![download](https://user-images.githubusercontent.com/41549829/148134612-bef143c9-8a91-4734-8e63-75eae4313a0f.png)
.

**Comment by Mamboleoo** [comment]
Could you share a little more details on your issue?
Did you do `npm install` first? Do you have any error in your console?

**Comment by iAmmarTahir** [comment]
Yes, I ran `npm install` first and there were no errors in console.

**Comment by iAmmarTahir** [comment]
I think you forgot to update the .parcelrc file. If you update it with this: `{
  "extends": ["@parcel/config-default"],
  "reporters":  ["...", "parcel-reporter-static-files-copy"]
}
`. Everything works perfectly fine. You can create a PR and merge it in `master`. Thanks.

**Comment by CeppGitHub** [comment]
Not working even with the "parcelrc" update :(
